export const ATTRACTION_CATEGORIES = [
  'All',
  'Landmark',
  'Historical',
  'Museum',
  'Temple',
  'Religious',
  'Beach',
  'Waterfall',
  'Mountain',
  'Viewpoint',
  'Nature',
  'Wildlife',
  'Adventure',
  'Park',
  'Shopping',
  'Food',
  'Cultural',
  'Art',
  'Entertainment',
  'Nightlife',
  'Photography',
  'Family',
  'Other',
];

export const ATTRACTION_TYPES = [
  'All',
  'Tourist Attraction',
  'Historical Site',
  'Natural Attraction',
  'Religious Site',
  'Adventure Activity',
  'Cultural Experience',
  'Food Experience',
  'Shopping Area',
  'Entertainment',
  'Outdoor Activity',
  'Indoor Activity',
];

export const ATTRACTION_FACILITIES = [
  'Parking',
  'Restrooms',
  'Food Court',
  'Wheelchair Access',
  'Guided Tours',
  'Photography',
  'WiFi',
  'Drinking Water',
  'Locker',
  'Public Transport',
  'Kids Area',
];

export const ATTRACTION_TAGS = [
  'Family Friendly',
  'Couples',
  'Solo Travel',
  'Budget Friendly',
  'Luxury',
  'Adventure',
  'Photography',
  'Nature',
  'History',
  'Culture',
  'Food',
  'Shopping',
  'Relaxation',
  'Weekend',
  'Must Visit',
  'Offbeat',
  'Instagrammable',
];

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Most Popular' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'price-low', label: 'Lowest Price' },
  { value: 'price-high', label: 'Highest Price' },
  { value: 'duration-short', label: 'Shortest Visit' },
  { value: 'duration-long', label: 'Longest Visit' },
  { value: 'newest', label: 'Newest' },
  { value: 'name', label: 'Alphabetical' },
];
