export const mockDestinations = [
  {
    id: 'dest-1',
    title: 'Goa',
    location: 'West Coast',
    country: 'India',
    rating: 4.8,
    reviewsCount: 1420,
    estimatedBudget: '₹15,000 - ₹25,000',
    category: 'Beach',
    duration: '4-6 Days',
    season: 'Nov - Feb',
    travelType: 'Leisure & Party',
    description: 'Sun-kissed golden beaches, vibrant nightlife, Portuguese heritage architecture, and delicious seafood.',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    tags: ['Beaches', 'Nightlife', 'Water Sports', 'Heritage'],
    isPopular: true,
  },
  {
    id: 'dest-2',
    title: 'Manali',
    location: 'Himachal Pradesh',
    country: 'India',
    rating: 4.7,
    reviewsCount: 980,
    estimatedBudget: '₹18,000 - ₹30,000',
    category: 'Mountain',
    duration: '5-7 Days',
    season: 'Oct - May',
    travelType: 'Adventure',
    description: 'Majestic snow-capped Himalayan peaks, Solang Valley adventures, cozy pine forest retreats, and scenic rivers.',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    tags: ['Snow', 'Mountains', 'Trekking', 'Solang Valley'],
    isPopular: true,
  },
  {
    id: 'dest-3',
    title: 'Jaipur',
    location: 'Rajasthan',
    country: 'India',
    rating: 4.9,
    reviewsCount: 2100,
    estimatedBudget: '₹12,000 - ₹22,000',
    category: 'Heritage',
    duration: '3-4 Days',
    season: 'Oct - Mar',
    travelType: 'Cultural',
    description: 'The iconic Pink City boasting grand forts, royal palaces, vibrant bazaars, and opulent Rajasthani culture.',
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    tags: ['Forts', 'Palaces', 'Culture', 'Shopping'],
    isPopular: true,
  },
  {
    id: 'dest-4',
    title: 'Kerala',
    location: 'South India',
    country: 'India',
    rating: 4.9,
    reviewsCount: 1750,
    estimatedBudget: '₹20,000 - ₹35,000',
    category: 'Nature',
    duration: '6-8 Days',
    season: 'Sep - Mar',
    travelType: 'Relaxation',
    description: 'Tranquil Alleppey backwaters houseboats, lush tea gardens of Munnar, and pristine tropical greenery.',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    tags: ['Backwaters', 'Tea Gardens', 'Ayurveda', 'Houseboat'],
    isPopular: true,
  },
  {
    id: 'dest-5',
    title: 'Kashmir',
    location: 'Jammu & Kashmir',
    country: 'India',
    rating: 4.9,
    reviewsCount: 1620,
    estimatedBudget: '₹25,000 - ₹45,000',
    category: 'Nature',
    duration: '5-7 Days',
    season: 'All Year',
    travelType: 'Romantic',
    description: 'Paradise on Earth featuring Dal Lake Shikara rides, Gulmarg snow slopes, and scenic tulip valleys.',
    imageUrl: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80',
    tags: ['Dal Lake', 'Gulmarg', 'Paradise', 'Shikara'],
    isPopular: true,
  },
  {
    id: 'dest-6',
    title: 'Udaipur',
    location: 'Rajasthan',
    country: 'India',
    rating: 4.8,
    reviewsCount: 1330,
    estimatedBudget: '₹16,000 - ₹28,000',
    category: 'Heritage',
    duration: '3-4 Days',
    season: 'Oct - Mar',
    travelType: 'Romantic',
    description: 'The City of Lakes adorned with fairy-tale Lake Palace, Lake Pichola boat rides, and romantic sunsets.',
    imageUrl: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f1c?auto=format&fit=crop&w=800&q=80',
    tags: ['Lakes', 'Palaces', 'Romance', 'Heritage'],
    isPopular: true,
  },
];
