require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Destination = require('../models/Destination');

const sampleDestinations = [
  {
    name: 'Goa',
    state: 'Goa',
    city: 'Panaji',
    country: 'India',
    shortDescription: 'Sun-kissed golden beaches, Portuguese heritage architecture, and vibrant nightlife.',
    description: 'Goa is India\'s premier beach destination on the Arabian Sea. Renowned for its palm-fringed coastline, historic Portuguese churches, vibrant night markets, and thrilling water sports, Goa offers a perfect blend of relaxation and adventure.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Beach', 'Adventure', 'Food', 'Relaxation', 'Party'],
    tags: ['Beaches', 'Nightlife', 'Water Sports', 'Heritage', 'Budget Friendly'],
    estimatedBudget: {
      minPerDay: 2500,
      maxPerDay: 6000,
      accommodation: { min: 1200, max: 3500 },
      food: { min: 600, max: 1500 },
      localTransport: { min: 400, max: 1000 },
      activities: { min: 300, max: 1000 },
    },
    bestTimeToVisit: {
      months: ['November', 'December', 'January', 'February'],
      season: 'Winter',
      description: 'Cool sea breezes and pleasant temperatures ideal for beach outings and outdoor festivals.',
    },
    averageDuration: { minDays: 4, maxDays: 6 },
    popularityScore: 98,
    rating: 4.8,
    reviewCount: 1420,
    latitude: 15.2993,
    longitude: 74.124,
    climate: 'Tropical Maritime',
    languages: ['Konkani', 'English', 'Hindi'],
    localTransport: 'Scooter rentals, auto-rickshaws, and local taxis are widely available.',
    safetyInformation: 'Generally very safe for tourists. Swim only in designated safe zones with active lifesavers.',
    travelTips: [
      'Rent a two-wheeler for convenient coastal travel.',
      'Try authentic Goan fish curry and Bebinca.',
      'Book beach shacks in advance during peak December season.',
    ],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Manali',
    state: 'Himachal Pradesh',
    city: 'Manali',
    country: 'India',
    shortDescription: 'Snow-capped Himalayan peaks, pine forests, and Solang Valley adventures.',
    description: 'Nestled in the Beas River Valley, Manali is a high-altitude Himalayan resort town known as a gateway for skiing in Solang Valley and trekking in Parvati Valley. It offers cozy wooden retreats and breathtaking mountain panoramas.',
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593181629936-11c609b8db9b?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Mountains', 'Adventure', 'Nature', 'Romantic'],
    tags: ['Snow', 'Mountains', 'Trekking', 'Solang Valley', 'Paragliding'],
    estimatedBudget: {
      minPerDay: 3000,
      maxPerDay: 7000,
      accommodation: { min: 1500, max: 4000 },
      food: { min: 700, max: 1500 },
      localTransport: { min: 400, max: 800 },
      activities: { min: 400, max: 1200 },
    },
    bestTimeToVisit: {
      months: ['October', 'November', 'December', 'January', 'February', 'March'],
      season: 'Winter & Spring',
      description: 'Ideal for snow activities, skiing, and panoramic mountain views.',
    },
    averageDuration: { minDays: 5, maxDays: 7 },
    popularityScore: 94,
    rating: 4.7,
    reviewCount: 980,
    latitude: 32.2432,
    longitude: 77.1892,
    climate: 'Cold Mountain',
    languages: ['Hindi', 'Pahari', 'English'],
    localTransport: 'Local taxis, auto-rickshaws, and walking along Mall Road.',
    safetyInformation: 'Check weather advisories and Rohtang Pass permits before heading up high passes.',
    travelTips: [
      'Obtain Rohtang Pass permits online beforehand.',
      'Carry adequate thermal layers in winter months.',
      'Visit Old Manali for peaceful cafes and local handicrafts.',
    ],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Jaipur',
    state: 'Rajasthan',
    city: 'Jaipur',
    country: 'India',
    shortDescription: 'The iconic Pink City featuring Amber Fort, City Palace, and vibrant bazaars.',
    description: 'Jaipur, the capital of Rajasthan, forms India\'s renowned Golden Triangle. Famous for its pink-painted historic buildings, grand royal fortresses, intricate palace architecture, and rich Rajasthani cuisine.',
    coverImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Historical', 'Cultural', 'Food', 'Shopping', 'Architecture'],
    tags: ['Forts', 'Palaces', 'Culture', 'Shopping', 'Heritage'],
    estimatedBudget: {
      minPerDay: 2000,
      maxPerDay: 5000,
      accommodation: { min: 1000, max: 2800 },
      food: { min: 500, max: 1200 },
      localTransport: { min: 300, max: 600 },
      activities: { min: 200, max: 800 },
    },
    bestTimeToVisit: {
      months: ['October', 'November', 'December', 'January', 'February', 'March'],
      season: 'Winter',
      description: 'Pleasant daytime temperatures ideal for fort exploration and open bazaar shopping.',
    },
    averageDuration: { minDays: 3, maxDays: 4 },
    popularityScore: 96,
    rating: 4.9,
    reviewCount: 2100,
    latitude: 26.9124,
    longitude: 75.7873,
    climate: 'Semi-Arid',
    languages: ['Rajasthani', 'Hindi', 'English'],
    localTransport: 'Jaipur Metro, auto-rickshaws, and e-rickshaws.',
    safetyInformation: 'Safe city. Mind official ticket counters at Amber Fort and City Palace to avoid unlicensed guides.',
    travelTips: [
      'Take an elephant or jeep ride to Amer Fort.',
      'Savor traditional Dal Baati Churma at Chokhi Dhani.',
      'Shop for Johari Bazaar textiles and Kundan jewelry.',
    ],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Kerala',
    state: 'Kerala',
    city: 'Alleppey & Munnar',
    country: 'India',
    shortDescription: 'Serene backwater houseboats, lush tea gardens, and tropical greenery.',
    description: 'Known as "God\'s Own Country", Kerala is a tropical paradise in South India renowned for its tranquil Alleppey backwaters, misty tea hill stations in Munnar, pristine beaches in Varkala, and Ayurvedic wellness retreats.',
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Nature', 'Relaxation', 'Family', 'Romantic', 'Cultural'],
    tags: ['Backwaters', 'Tea Gardens', 'Ayurveda', 'Houseboat', 'Nature Escape'],
    estimatedBudget: {
      minPerDay: 3000,
      maxPerDay: 8000,
      accommodation: { min: 1500, max: 4500 },
      food: { min: 600, max: 1500 },
      localTransport: { min: 500, max: 1200 },
      activities: { min: 400, max: 1500 },
    },
    bestTimeToVisit: {
      months: ['September', 'October', 'November', 'December', 'January', 'February', 'March'],
      season: 'Post-Monsoon & Winter',
      description: 'Lush green landscapes and pleasant backwater cruising weather.',
    },
    averageDuration: { minDays: 6, maxDays: 8 },
    popularityScore: 97,
    rating: 4.9,
    reviewCount: 1750,
    latitude: 9.4981,
    longitude: 76.3388,
    climate: 'Tropical Wet',
    languages: ['Malayalam', 'English', 'Hindi'],
    localTransport: 'Ferries, state buses, private taxis, and houseboats.',
    safetyInformation: 'Extremely safe and hospitable travel destination.',
    travelTips: [
      'Book an overnight houseboat cruise in Alleppey.',
      'Visit spice plantations in Thekkady.',
      'Experience authentic Kerala Sadya served on a banana leaf.',
    ],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Kashmir',
    state: 'Jammu & Kashmir',
    city: 'Srinagar',
    country: 'India',
    shortDescription: 'Paradise on Earth with Dal Lake Shikara rides, Gulmarg snow slopes, and tulip gardens.',
    description: 'Kashmir is globally celebrated for its majestic natural beauty, alpine meadows, pristine snow-capped mountains, serene Dal Lake houseboats, and colorful spring tulip gardens.',
    coverImage: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Nature', 'Romantic', 'Mountains', 'Adventure'],
    tags: ['Dal Lake', 'Gulmarg', 'Paradise', 'Shikara', 'Snow'],
    estimatedBudget: {
      minPerDay: 4000,
      maxPerDay: 9000,
      accommodation: { min: 2000, max: 5000 },
      food: { min: 800, max: 1800 },
      localTransport: { min: 600, max: 1400 },
      activities: { min: 600, max: 1800 },
    },
    bestTimeToVisit: {
      months: ['April', 'May', 'June', 'September', 'October', 'December', 'January'],
      season: 'All Seasons',
      description: 'Spring for tulips, summer for green valleys, and winter for Gulmarg skiing.',
    },
    averageDuration: { minDays: 5, maxDays: 7 },
    popularityScore: 99,
    rating: 4.9,
    reviewCount: 1620,
    latitude: 34.0837,
    longitude: 74.7973,
    climate: 'Subtropical / Alpine',
    languages: ['Kashmiri', 'Urdu', 'Hindi', 'English'],
    localTransport: 'Shikaras on lakes, union taxis for inter-city travel.',
    safetyInformation: 'Follow local advisories and stick to established tourist circuits in Srinagar, Gulmarg, and Pahalgam.',
    travelTips: [
      'Take a sunset Shikara ride on Dal Lake.',
      'Ride the Gulmarg Gondola to Phase 2.',
      'Savor traditional Kashmiri Kahwa and Wazwan.',
    ],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Udaipur',
    state: 'Rajasthan',
    city: 'Udaipur',
    country: 'India',
    shortDescription: 'The City of Lakes adorned with fairy-tale Lake Palace and Lake Pichola boat rides.',
    description: 'Known as the Venice of the East, Udaipur is renowned for its romantic lakes, grand City Palace complex, marble mansions, and scenic Aravalli mountain views.',
    coverImage: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f1c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1615836245337-f5b9b2303f1c?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Heritage', 'Romantic', 'Historical', 'Luxury'],
    tags: ['Lakes', 'Palaces', 'Romance', 'Heritage', 'Couples'],
    estimatedBudget: {
      minPerDay: 3000,
      maxPerDay: 7500,
      accommodation: { min: 1500, max: 4000 },
      food: { min: 600, max: 1500 },
      localTransport: { min: 400, max: 800 },
      activities: { min: 500, max: 1200 },
    },
    bestTimeToVisit: {
      months: ['October', 'November', 'December', 'January', 'February', 'March'],
      season: 'Winter',
      description: 'Pleasant lakeside breezes and comfortable weather for palace sightseeing.',
    },
    averageDuration: { minDays: 3, maxDays: 4 },
    popularityScore: 92,
    rating: 4.8,
    reviewCount: 1330,
    latitude: 24.5854,
    longitude: 73.7125,
    climate: 'Semi-Arid',
    languages: ['Mewari', 'Hindi', 'English'],
    localTransport: 'Auto-rickshaws, walking around old city lanes, lake ferry boats.',
    safetyInformation: 'Very safe city for solo travelers and couples.',
    travelTips: [
      'Watch the sunset from Ambrai Ghat or a rooftop cafe.',
      'Take a boat cruise to Jagmandir Island.',
    ],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Rishikesh',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    country: 'India',
    shortDescription: 'Yoga capital of the world, river rafting on the Ganges, and Himalayan foothills.',
    description: 'Located at the foothills of the Himalayas along the holy Ganges River, Rishikesh is famed for yoga ashrams, spiritual evening Ganga Aarti at Triveni Ghat, and white-water river rafting thrills.',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Adventure', 'Religious', 'Nature', 'Relaxation'],
    tags: ['River Rafting', 'Yoga', 'Ganges', 'Spiritual', 'Trekking', 'Budget Friendly'],
    estimatedBudget: {
      minPerDay: 1800,
      maxPerDay: 4000,
      accommodation: { min: 800, max: 2200 },
      food: { min: 400, max: 900 },
      localTransport: { min: 200, max: 400 },
      activities: { min: 400, max: 1000 },
    },
    bestTimeToVisit: {
      months: ['September', 'October', 'November', 'March', 'April', 'May'],
      season: 'Autumn & Spring',
      description: 'Ideal water levels for rafting and pleasant weather for yoga workshops.',
    },
    averageDuration: { minDays: 3, maxDays: 5 },
    popularityScore: 90,
    rating: 4.7,
    reviewCount: 1100,
    latitude: 30.0869,
    longitude: 78.2676,
    climate: 'Subtropical',
    languages: ['Hindi', 'Garhwali', 'English'],
    localTransport: 'Shared auto-rickshaws (Vikrams) and walking across Laxman Jhula.',
    safetyInformation: 'Follow river rafting safety instructions strictly and wear life jackets.',
    travelTips: [
      'Attend the evening Ganga Aarti at Parmarth Niketan.',
      'Try cliff jumping and white water rafting in Shivpuri.',
    ],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Andaman Islands',
    state: 'Andaman & Nicobar',
    city: 'Port Blair & Havelock',
    country: 'India',
    shortDescription: 'Exotic turquoise waters, Radhanagar Beach, scuba diving, and coral reefs.',
    description: 'An archipelago in the Bay of Bengal, the Andaman Islands offer tropical rainforests, white sand beaches, world-class scuba diving, and deep marine biodiversity.',
    coverImage: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80',
    ],
    categories: ['Beach', 'Adventure', 'Nature', 'Luxury', 'Romantic'],
    tags: ['Scuba Diving', 'Radhanagar Beach', 'Corals', 'Islands', 'Water Sports'],
    estimatedBudget: {
      minPerDay: 4500,
      maxPerDay: 10000,
      accommodation: { min: 2200, max: 5500 },
      food: { min: 800, max: 2000 },
      localTransport: { min: 600, max: 1500 },
      activities: { min: 900, max: 2500 },
    },
    bestTimeToVisit: {
      months: ['October', 'November', 'December', 'January', 'February', 'March', 'April', 'May'],
      season: 'Winter & Summer',
      description: 'Clear ocean water ideal for underwater diving and sea walking.',
    },
    averageDuration: { minDays: 5, maxDays: 7 },
    popularityScore: 93,
    rating: 4.9,
    reviewCount: 890,
    latitude: 11.6233,
    longitude: 92.7265,
    climate: 'Tropical Monsoonal',
    languages: ['Hindi', 'Bengali', 'English', 'Tamil'],
    localTransport: 'Inter-island ferries (Makruzz), rental scooters, and cabs.',
    safetyInformation: 'Obtain required RAP permits where applicable. Avoid swimming in prohibited crocodile zones.',
    travelTips: [
      'Visit Radhanagar Beach on Havelock Island for sunset.',
      'Book inter-island ferry tickets well in advance.',
    ],
    isFeatured: true,
    isActive: true,
  },
];

const seedDestinations = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/trippilot';
    await mongoose.connect(mongoUri);
    console.log('[Seed Destinations] Connected to MongoDB');

    for (const destData of sampleDestinations) {
      const slug = Destination.generateSlug(destData.name);
      await Destination.findOneAndUpdate(
        { slug },
        { ...destData, slug },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      console.log(`[Seed] Seeded destination: ${destData.name} (slug: ${slug})`);
    }

    console.log('[Seed Destinations] Success! Sample destinations seeded.');
    process.exit(0);
  } catch (error) {
    console.error('[Seed Destinations Error]:', error);
    process.exit(1);
  }
};

seedDestinations();
