const ATTRACTION_CATEGORIES = [
  'Landmark',
  'Historical',
  'Museum',
  'Temple',
  'Religious',
  'Beach',
  'Waterfall',
  'Mountain',
  'Viewpoint',
  'Nature',
  'Wildlife',
  'Adventure',
  'Park',
  'Shopping',
  'Food',
  'Cultural',
  'Art',
  'Entertainment',
  'Nightlife',
  'Photography',
  'Family',
  'Other',
];

const ATTRACTION_TYPES = [
  'Tourist Attraction',
  'Historical Site',
  'Natural Attraction',
  'Religious Site',
  'Adventure Activity',
  'Cultural Experience',
  'Food Experience',
  'Shopping Area',
  'Entertainment',
  'Outdoor Activity',
  'Indoor Activity',
];

const ATTRACTION_FACILITIES = [
  'Parking',
  'Restrooms',
  'Food Court',
  'Wheelchair Access',
  'Guided Tours',
  'Photography',
  'WiFi',
  'Drinking Water',
  'Locker',
  'Public Transport',
  'Kids Area',
];

const ATTRACTION_TAGS = [
  'Family Friendly',
  'Couples',
  'Solo Travel',
  'Budget Friendly',
  'Luxury',
  'Adventure',
  'Photography',
  'Nature',
  'History',
  'Culture',
  'Food',
  'Shopping',
  'Relaxation',
  'Weekend',
  'Must Visit',
  'Offbeat',
  'Instagrammable',
];

module.exports = {
  ATTRACTION_CATEGORIES,
  ATTRACTION_TYPES,
  ATTRACTION_FACILITIES,
  ATTRACTION_TAGS,
};
